### ISSUE TITLE
Instruction in README.md confusing

### ISSUE THREAD

**Issue by jgodse** [copiousfreetime/amalgalite#30]
One of the instructions in README.md reads:

     5.  bundle 6 rake cross native gem

A bug in the Markdown syntax caused this. What you probably meant to say was

     5. bundle
     6. rake cross native gem

**Comment by jgodse** [comment]
https://github.com/copiousfreetime/amalgalite/pull/31 - This pull reqvest solves the problem.

**Comment by jgodse** [comment]
https://travis-ci.org/copiousfreetime/amalgalite/jobs/140047126 - How does a one-character change in a README.md file trigger a build failure?

**Comment by copiousfreetime** [comment]
Its not the readme for sure, I've had brittle build situations with travis and extensions off and on over the years. Something has changed since the last time it ran builds so who knows. I'll figure it out :-).
