### ISSUE TITLE
Different ruby compatibility depending on platform

### ISSUE THREAD

**Issue by swistak35** [copiousfreetime/amalgalite#41]
Hi,
Was that intentional that [1.7.0 platform version](https://rubygems.org/gems/amalgalite/versions/1.7.0) was released with ruby requirements being just "ruby >= 2.2.2", but [mingw versions](https://rubygems.org/gems/amalgalite/versions/1.7.0-x86-mingw32) with ruby requirements "ruby >= 2.2.2 AND ruby < 2.7.dev"? That makes it impossible to install on 2.7 ruby installation.

If that was accidental, could you please release mingw versions without that additional requirement (it's ok if it's 1.7.1, I don't care about 1.7.0 specifically)?

**Comment by copiousfreetime** [comment]
@swistak35 that was my mistake - I dropped the ball on this, got sidetracked with a lot of other things, I'm building this now and should have releases pushed by tomorrow - also updating to the latest sqlite.

**Comment by copiousfreetime** [comment]
@swistak35 do you need the cross-compiled binaries for windows or is the ruby version good enough for you? I'm on an M1 now and I haven't gotten sempahore ci worked out correctly to get it wired up with rack-compiler-dock to build the windows binaries yet. If you're good with the ruby version that builds the extensions locally for you, then I can push out that tomorrow.

**Comment by swistak35** [comment]
I did use the compiled version previously, so that would be best, but I do have a windows devkit compiler set up on my machine, so I guess it should work (I can't really be sure of anything with ruby on windows :smile:). Let's find out. As I understand there is possibility that the precompiled versions will be available at some point :)

**Comment by copiousfreetime** [comment]
@swistak35 can you test out this pre-release and see if it works for you. I'm testing out building binaries using a semaphore workflow - https://github.com/copiousfreetime/amalgalite/releases/tag/v1.7.3-pre -- I'll remove it once you've given it a :+1: or :-1: I'm not sure which platform  and ruby you're on, but one of those 3 should be valid.

**Comment by swistak35** [comment]
Unfortunately things using `amalgalite` gem aren't covered well with specs so I cannot say "everything works as before", but I did a check of installing the fat version (`x86-mingw32` one to be specific) on windows and fiddled with it in `irb` for a moment, creating a db, loading some schema, making queries -- and it works :)

**Comment by copiousfreetime** [comment]
Awesome, I'll push out releases this weekend then

**Comment by copiousfreetime** [comment]
@swistak35 FYI - v1.8.0 pushed to rubygems let me know if there are any issues.

**Comment by swistak35** [comment]
Perfect, thanks!
